SHELL:=/bin/bash
#######################################
install:
	chmod u+x install_clapack.sh
	./install_clapack.sh
	chmod -x install_clapack.sh

#######################################
clean:
	rm -rf CLAPACK
	rm -rf ATLAS
	chmod -x install_clapack.sh
	rm -rf clapack.tgz
